import {
  BookOpen, Briefcase, Users, Target,
  MessageSquare, Repeat, Globe, HandHeart, TrendingUp,
} from "lucide-react";
import { LW_TOPICS, resolveLWTopicSlug } from "./labourWelfareUnits";
import { MBA_ECO_TOPICS, BBA_ECO_TOPICS } from "./economicsUnits";

export const DISCIPLINES = [
  {
    value: "hrm",
    label: "Human Resource Management",
    short: "HRM",
    icon: BookOpen,
    color: "bg-[#F2F1EF] border-[#DCD9D3] text-[#17181C]",
    activeColor: "bg-[#17181C] border-[#17181C] text-white",
    iconBg: "bg-[#E8E6E2]",
    iconColor: "text-[#17181C]",
    description: "Recruitment, compensation, SHRM, HR analytics, labour law",
    topics: [
      { label: "Compensation & Benefits",    slug: "compensation-and-benefits" },
      { label: "Performance Management",     slug: "performance-management" },
      { label: "Recruitment & Selection",    slug: "recruitment-and-selection" },
      { label: "Functions of HR",            slug: "functions-of-hr" },
      { label: "Industrial Relations",       slug: "industrial-relations" },
      { label: "HRIS & SHRM",               slug: "hris-and-shrm" },
      { label: "HR Analytics",              slug: "hr-analytics" },
      { label: "HR Planning",               slug: "human-resource-planning" },
      { label: "Evolution of HRM",          slug: "evolution-of-hrm" },
      { label: "Training & Development",    slug: "training-and-development" },
      { label: "Employee Relations",        slug: "employee-relations" },
      { label: "Talent Management",         slug: "talent-management" },
    ],
  },
  {
    value: "ob",
    label: "Organisational Behaviour",
    short: "OB",
    icon: Users,
    color: "bg-[#F7F5F2] border-[#DCD9D3] text-[#4A4A4F]",
    activeColor: "bg-[#4A4A4F] border-[#4A4A4F] text-white",
    iconBg: "bg-[#E8E6E2]",
    iconColor: "text-[#4A4A4F]",
    description: "Individual behaviour, motivation, leadership, group dynamics",
    topics: [
      { label: "Foundations of OB",         slug: "foundations-of-ob" },
      { label: "Individual Behaviour",       slug: "individual-behaviour" },
      { label: "Personality",               slug: "personality" },
      { label: "Perception",                slug: "perception" },
      { label: "Motivation",                slug: "motivation" },
      { label: "Learning",                  slug: "learning" },
      { label: "Group Dynamics",            slug: "group-dynamics" },
      { label: "Leadership",                slug: "leadership" },
      { label: "Organisational Culture",    slug: "organizational-culture" },
      { label: "Change Management",         slug: "change-management" },
      { label: "Conflict & Stress",         slug: "conflict-and-stress" },
      { label: "Power & Politics",          slug: "power-and-politics" },
    ],
  },
  {
    value: "sm",
    label: "Strategic Management",
    short: "SM",
    icon: Target,
    color: "bg-[#FDF4F2] border-[#F0C8C1] text-[#8C2A1E]",
    activeColor: "bg-[#E34234] border-[#E34234] text-white",
    iconBg: "bg-[#F8DED8]",
    iconColor: "text-[#B23223]",
    description: "SWOT, Porter's five forces, strategy formulation & evaluation",
    topics: [
      { label: "Nature & Scope of SM",          slug: "nature-and-scope-of-sm" },
      { label: "Strategic Intent",              slug: "strategic-intent" },
      { label: "Environmental Scanning",        slug: "environmental-scanning" },
      { label: "Strategic Analysis",            slug: "strategic-analysis" },
      { label: "Strategy Formulation",          slug: "strategy-formulation" },
      { label: "Strategy Implementation",       slug: "strategy-implementation" },
      { label: "Strategy Evaluation & Control", slug: "strategy-evaluation" },
      { label: "Corporate Governance",          slug: "corporate-governance" },
      { label: "Competitive Strategies",        slug: "competitive-strategies" },
      { label: "Business-Level Strategy",       slug: "business-level-strategy" },
      { label: "Corporate-Level Strategy",      slug: "corporate-level-strategy" },
    ],
  },
  {
    value: "pom",
    label: "Principles of Management",
    short: "POM",
    icon: Briefcase,
    color: "bg-[#EFEDE9] border-[#D5D1CA] text-[#0B0C0E]",
    activeColor: "bg-[#0B0C0E] border-[#0B0C0E] text-white",
    iconBg: "bg-[#E8E6E2]",
    iconColor: "text-[#0B0C0E]",
    description: "Planning, organising, directing, controlling, Fayol & Taylor",
    topics: [
      { label: "Planning",                  slug: "planning" },
      { label: "Organizing",               slug: "organizing" },
      { label: "Staffing",                  slug: "staffing" },
      { label: "Directing",                 slug: "directing" },
      { label: "Controlling",               slug: "controlling" },
      { label: "Coordination",              slug: "coordination" },
      { label: "Decision Making",           slug: "decision-making" },
      { label: "Principles of Fayol & Taylor", slug: "fayol-taylor" },
      { label: "Business Ethics",           slug: "business-ethics" },
      { label: "Management Theories",      slug: "management-theories" },
      { label: "MBO & MBE",                slug: "mbo-mbe" },
    ],
  },
  {
    value: "bc",
    label: "Business Communication",
    short: "BC",
    icon: MessageSquare,
    color: "bg-[#F7F5F2] border-[#DCD9D3] text-[#4A4A4F]",
    activeColor: "bg-[#6B6B70] border-[#6B6B70] text-white",
    iconBg: "bg-[#E8E6E2]",
    iconColor: "text-[#6B6B70]",
    description: "Written, verbal, cross-cultural & digital business communication",
    topics: [
      { label: "Intro to Business Communication",  slug: "introduction-to-bc" },
      { label: "Communication Process & Barriers", slug: "communication-process-barriers" },
      { label: "Types of Communication",           slug: "types-of-communication" },
      { label: "Business Letters & Reports",       slug: "business-letters-reports" },
      { label: "Email & Digital Communication",    slug: "email-digital-communication" },
      { label: "Presentation Skills",              slug: "presentation-skills" },
      { label: "Negotiation & Persuasion",         slug: "negotiation-persuasion" },
      { label: "Cross-cultural Communication",     slug: "cross-cultural-communication" },
      { label: "Corporate Communication",          slug: "corporate-communication" },
    ],
  },
  {
    value: "odcm",
    label: "OD & Change Management",
    short: "OD & CM",
    icon: Repeat,
    color: "bg-[#FDF4F2] border-[#F0C8C1] text-[#8C2A1E]",
    activeColor: "bg-[#B23223] border-[#B23223] text-white",
    iconBg: "bg-[#F8DED8]",
    iconColor: "text-[#B23223]",
    description: "OD interventions, change models, managing resistance",
    topics: [
      { label: "Introduction to OD",             slug: "introduction-to-od" },
      { label: "OD Interventions",               slug: "od-interventions" },
      { label: "Action Research Model",          slug: "action-research-model" },
      { label: "Change Management Models",       slug: "change-management-models" },
      { label: "Managing Resistance to Change",  slug: "managing-resistance" },
      { label: "Planned vs Emergent Change",     slug: "planned-vs-emergent" },
      { label: "Organisational Transformation",  slug: "organizational-transformation" },
      { label: "Team & Group Interventions",     slug: "team-group-interventions" },
      { label: "Future of OD & Change",          slug: "future-of-od" },
    ],
  },
  {
    value: "ghr",
    label: "International HRM Practices",
    short: "International HRM",
    icon: Globe,
    color: "bg-[#EFEDE9] border-[#D5D1CA] text-[#0B0C0E]",
    activeColor: "bg-[#0B0C0E] border-[#0B0C0E] text-white",
    iconBg: "bg-[#E8E6E2]",
    iconColor: "text-[#0B0C0E]",
    description: "Expatriate management, international staffing, MNCs & diversity",
    topics: [
      { label: "Introduction to International HRM", slug: "introduction-to-ghrm" },
      { label: "International Staffing",            slug: "international-staffing" },
      { label: "Expatriate Management",             slug: "expatriate-management" },
      { label: "Cross-Cultural Management",         slug: "cross-cultural-management" },
      { label: "Global Compensation",               slug: "global-compensation" },
      { label: "International Training & Dev",      slug: "international-training" },
      { label: "International Labour Standards",    slug: "international-labour-standards" },
      { label: "MNCs & HR Practices",              slug: "mncs-hr-practices" },
      { label: "Global Workforce Diversity",        slug: "global-workforce-diversity" },
    ],
  },
  {
    value: "mba-eco",
    label: "Managerial Economics",
    short: "MBA Eco",
    icon: TrendingUp,
    color: "bg-[#F0FDF4] border-[#BBF7D0] text-[#166534]",
    activeColor: "bg-[#166534] border-[#166534] text-white",
    iconBg: "bg-[#DCFCE7]",
    iconColor: "text-[#166534]",
    description: "Demand analysis, production & cost, market structures, macroeconomics, Indian economy",
    topics: MBA_ECO_TOPICS,
  },
  {
    value: "bba-eco",
    label: "Business Economics",
    short: "BBA Eco",
    icon: TrendingUp,
    color: "bg-[#EEF2FF] border-[#C7D2FE] text-[#3730A3]",
    activeColor: "bg-[#3730A3] border-[#3730A3] text-white",
    iconBg: "bg-[#E0E7FF]",
    iconColor: "text-[#3730A3]",
    description: "Demand & supply, market equilibrium, production & cost, market structures, national income",
    topics: BBA_ECO_TOPICS,
  },
  {
    value: "lw",
    label: "Labour Welfare (UGC NET/JRF)",
    short: "Labour Welfare",
    icon: HandHeart,
    color: "bg-[#EFEDE9] border-[#D5D1CA] text-[#0B0C0E]",
    activeColor: "bg-[#0B0C0E] border-[#0B0C0E] text-white",
    iconBg: "bg-[#E8E6E2]",
    iconColor: "text-[#0B0C0E]",
    description: "UGC NET/JRF Paper II (Subject Code 55) — Management, HRM, HRD & IHRM, OB, Industrial Relations & Trade Unions, Industrial Disputes, Labour Legislation, Wages, Labour Welfare & Social Security, Labour Market, Units I–X",
    topics: LW_TOPICS,
  },
] as const;

export type DisciplineValue = typeof DISCIPLINES[number]["value"];

export function getDiscipline(value: string) {
  return DISCIPLINES.find(d => d.value === value);
}

export function getTopicLabel(slug: string) {
  // Labour Welfare content saved under a pre-2026 syllabus slug should show
  // its current topic's label, not the raw legacy slug.
  const resolved = resolveLWTopicSlug(slug);
  for (const d of DISCIPLINES) {
    const t = d.topics.find(t => t.slug === resolved);
    if (t) return t.label;
  }
  return slug;
}
