import {
  BookOpen, Languages, Briefcase, Users, Target,
  MessageSquare, Scale, Repeat, Globe, HandHeart,
} from "lucide-react";
import { LW_TOPICS } from "./labourWelfareUnits";

export const DISCIPLINES = [
  {
    value: "hrm",
    label: "Human Resource Management",
    short: "HRM",
    icon: BookOpen,
    color: "bg-[#EEF0F8] border-[#C9D8E8] text-[#1F4E79]",
    activeColor: "bg-[#1F4E79] border-[#1F4E79] text-white",
    iconBg: "bg-[#DCE6F1]",
    iconColor: "text-[#1F4E79]",
    description: "Recruitment, compensation, SHRM, HR analytics, labour law",
    topics: [
      { label: "Compensation & Benefits",    slug: "compensation-and-benefits" },
      { label: "Performance Management",     slug: "performance-management" },
      { label: "Recruitment & Selection",    slug: "recruitment-and-selection" },
      { label: "Functions of HR",            slug: "functions-of-hr" },
      { label: "Industrial Relations",       slug: "industrial-relations" },
      { label: "HRIS & SHRM",               slug: "hris-and-shrm" },
      { label: "HR Analytics",              slug: "hr-analytics" },
      { label: "HR Planning",               slug: "human-resource-planning" },
      { label: "Evolution of HRM",          slug: "evolution-of-hrm" },
      { label: "Training & Development",    slug: "training-and-development" },
      { label: "Employee Relations",        slug: "employee-relations" },
      { label: "Talent Management",         slug: "talent-management" },
    ],
  },
  {
    value: "ob",
    label: "Organisational Behaviour",
    short: "OB",
    icon: Users,
    color: "bg-[#F2F6FA] border-[#C9D8E8] text-[#3D6C98]",
    activeColor: "bg-[#3D6C98] border-[#3D6C98] text-white",
    iconBg: "bg-[#DCE6F1]",
    iconColor: "text-[#3D6C98]",
    description: "Individual behaviour, motivation, leadership, group dynamics",
    topics: [
      { label: "Foundations of OB",         slug: "foundations-of-ob" },
      { label: "Individual Behaviour",       slug: "individual-behaviour" },
      { label: "Personality",               slug: "personality" },
      { label: "Perception",                slug: "perception" },
      { label: "Motivation",                slug: "motivation" },
      { label: "Learning",                  slug: "learning" },
      { label: "Group Dynamics",            slug: "group-dynamics" },
      { label: "Leadership",                slug: "leadership" },
      { label: "Organisational Culture",    slug: "organizational-culture" },
      { label: "Change Management",         slug: "change-management" },
      { label: "Conflict & Stress",         slug: "conflict-and-stress" },
      { label: "Power & Politics",          slug: "power-and-politics" },
    ],
  },
  {
    value: "sm",
    label: "Strategic Management",
    short: "SM",
    icon: Target,
    color: "bg-[#FAF5EA] border-[#E8DCC0] text-[#8F6D33]",
    activeColor: "bg-[#C7994A] border-[#C7994A] text-white",
    iconBg: "bg-[#F3EAD5]",
    iconColor: "text-[#A9823F]",
    description: "SWOT, Porter's five forces, strategy formulation & evaluation",
    topics: [
      { label: "Nature & Scope of SM",          slug: "nature-and-scope-of-sm" },
      { label: "Strategic Intent",              slug: "strategic-intent" },
      { label: "Environmental Scanning",        slug: "environmental-scanning" },
      { label: "Strategic Analysis",            slug: "strategic-analysis" },
      { label: "Strategy Formulation",          slug: "strategy-formulation" },
      { label: "Strategy Implementation",       slug: "strategy-implementation" },
      { label: "Strategy Evaluation & Control", slug: "strategy-evaluation" },
      { label: "Corporate Governance",          slug: "corporate-governance" },
      { label: "Competitive Strategies",        slug: "competitive-strategies" },
      { label: "Business-Level Strategy",       slug: "business-level-strategy" },
      { label: "Corporate-Level Strategy",      slug: "corporate-level-strategy" },
    ],
  },
  {
    value: "pom",
    label: "Principles of Management",
    short: "POM",
    icon: Briefcase,
    color: "bg-[#E9EEF5] border-[#C0CEDD] text-[#0D2A45]",
    activeColor: "bg-[#0D2A45] border-[#0D2A45] text-white",
    iconBg: "bg-[#DCE6F1]",
    iconColor: "text-[#0D2A45]",
    description: "Planning, organising, directing, controlling, Fayol & Taylor",
    topics: [
      { label: "Planning",                  slug: "planning" },
      { label: "Organizing",               slug: "organizing" },
      { label: "Staffing",                  slug: "staffing" },
      { label: "Directing",                 slug: "directing" },
      { label: "Controlling",               slug: "controlling" },
      { label: "Coordination",              slug: "coordination" },
      { label: "Decision Making",           slug: "decision-making" },
      { label: "Principles of Fayol & Taylor", slug: "fayol-taylor" },
      { label: "Business Ethics",           slug: "business-ethics" },
      { label: "Management Theories",      slug: "management-theories" },
      { label: "MBO & MBE",                slug: "mbo-mbe" },
    ],
  },
  {
    value: "bc",
    label: "Business Communication",
    short: "BC",
    icon: MessageSquare,
    color: "bg-[#F2F6FA] border-[#C9D8E8] text-[#3D6C98]",
    activeColor: "bg-[#5B8AB8] border-[#5B8AB8] text-white",
    iconBg: "bg-[#DCE6F1]",
    iconColor: "text-[#5B8AB8]",
    description: "Written, verbal, cross-cultural & digital business communication",
    topics: [
      { label: "Intro to Business Communication",  slug: "introduction-to-bc" },
      { label: "Communication Process & Barriers", slug: "communication-process-barriers" },
      { label: "Types of Communication",           slug: "types-of-communication" },
      { label: "Business Letters & Reports",       slug: "business-letters-reports" },
      { label: "Email & Digital Communication",    slug: "email-digital-communication" },
      { label: "Presentation Skills",              slug: "presentation-skills" },
      { label: "Negotiation & Persuasion",         slug: "negotiation-persuasion" },
      { label: "Cross-cultural Communication",     slug: "cross-cultural-communication" },
      { label: "Corporate Communication",          slug: "corporate-communication" },
    ],
  },
  {
    value: "cgbe",
    label: "Corporate Governance & Business Ethics",
    short: "CG & BE",
    icon: Scale,
    color: "bg-[#EEF0F8] border-[#C9D8E8] text-[#1F4E79]",
    activeColor: "bg-[#1F4E79] border-[#1F4E79] text-white",
    iconBg: "bg-[#DCE6F1]",
    iconColor: "text-[#1F4E79]",
    description: "Board governance, CSR, ESG, ethical decision-making",
    topics: [
      { label: "Intro to Corporate Governance",   slug: "introduction-to-cg" },
      { label: "Board of Directors & Committees", slug: "board-of-directors" },
      { label: "Shareholders & Stakeholders",     slug: "shareholders-stakeholders" },
      { label: "Governance Codes & Regulations",  slug: "governance-codes" },
      { label: "Business Ethics & CSR",           slug: "business-ethics-csr" },
      { label: "Ethical Decision Making",         slug: "ethical-decision-making" },
      { label: "Corporate Social Responsibility", slug: "corporate-social-responsibility" },
      { label: "Sustainability & ESG",            slug: "sustainability-esg" },
      { label: "Insider Trading & Fraud",         slug: "insider-trading-fraud" },
    ],
  },
  {
    value: "odcm",
    label: "OD & Change Management",
    short: "OD & CM",
    icon: Repeat,
    color: "bg-[#FAF5EA] border-[#E8DCC0] text-[#8F6D33]",
    activeColor: "bg-[#A9823F] border-[#A9823F] text-white",
    iconBg: "bg-[#F3EAD5]",
    iconColor: "text-[#A9823F]",
    description: "OD interventions, change models, managing resistance",
    topics: [
      { label: "Introduction to OD",             slug: "introduction-to-od" },
      { label: "OD Interventions",               slug: "od-interventions" },
      { label: "Action Research Model",          slug: "action-research-model" },
      { label: "Change Management Models",       slug: "change-management-models" },
      { label: "Managing Resistance to Change",  slug: "managing-resistance" },
      { label: "Planned vs Emergent Change",     slug: "planned-vs-emergent" },
      { label: "Organisational Transformation",  slug: "organizational-transformation" },
      { label: "Team & Group Interventions",     slug: "team-group-interventions" },
      { label: "Future of OD & Change",          slug: "future-of-od" },
    ],
  },
  {
    value: "ghr",
    label: "Global HR Practices",
    short: "Global HR",
    icon: Globe,
    color: "bg-[#E9EEF5] border-[#C0CEDD] text-[#0D2A45]",
    activeColor: "bg-[#0D2A45] border-[#0D2A45] text-white",
    iconBg: "bg-[#DCE6F1]",
    iconColor: "text-[#0D2A45]",
    description: "Expatriate management, international staffing, MNCs & diversity",
    topics: [
      { label: "Introduction to Global HRM",        slug: "introduction-to-ghrm" },
      { label: "International Staffing",            slug: "international-staffing" },
      { label: "Expatriate Management",             slug: "expatriate-management" },
      { label: "Cross-Cultural Management",         slug: "cross-cultural-management" },
      { label: "Global Compensation",               slug: "global-compensation" },
      { label: "International Training & Dev",      slug: "international-training" },
      { label: "International Labour Standards",    slug: "international-labour-standards" },
      { label: "MNCs & HR Practices",              slug: "mncs-hr-practices" },
      { label: "Global Workforce Diversity",        slug: "global-workforce-diversity" },
    ],
  },
  {
    value: "english",
    label: "English for Management",
    short: "English",
    icon: Languages,
    color: "bg-[#F2F6FA] border-[#C9D8E8] text-[#3D6C98]",
    activeColor: "bg-[#3D6C98] border-[#3D6C98] text-white",
    iconBg: "bg-[#DCE6F1]",
    iconColor: "text-[#3D6C98]",
    description: "Vocabulary, grammar, reading comprehension, writing skills",
    topics: [
      { label: "Vocabulary",              slug: "vocabulary" },
      { label: "Grammar",                 slug: "grammar" },
      { label: "Reading Comprehension",   slug: "reading-comprehension" },
      { label: "Writing Skills",          slug: "writing-skills" },
      { label: "Verbal Ability",          slug: "verbal-ability" },
      { label: "Synonyms & Antonyms",     slug: "synonyms-antonyms" },
      { label: "Idioms & Phrases",        slug: "idioms-phrases" },
    ],
  },
  {
    value: "lw",
    label: "Labour Welfare (UGC NET)",
    short: "Labour Welfare",
    icon: HandHeart,
    color: "bg-[#E9EEF5] border-[#C0CEDD] text-[#0D2A45]",
    activeColor: "bg-[#0D2A45] border-[#0D2A45] text-white",
    iconBg: "bg-[#DCE6F1]",
    iconColor: "text-[#0D2A45]",
    description: "UGC NET Paper II (Subject Code 55) — Personnel Management, HRD, Industrial Relations, Trade Unions, Labour Legislation, Labour Welfare & Labour Market, Units I–X",
    topics: LW_TOPICS,
  },
] as const;

export type DisciplineValue = typeof DISCIPLINES[number]["value"];

export function getDiscipline(value: string) {
  return DISCIPLINES.find(d => d.value === value);
}

export function getTopicLabel(slug: string) {
  for (const d of DISCIPLINES) {
    const t = d.topics.find(t => t.slug === slug);
    if (t) return t.label;
  }
  return slug;
}
